hr_tech/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('account/', include('account.urls')),

    path('', include('dashboard.urls')),

    path('candidate/', include('candidat.urls')),

    path('mission/', include('mission.urls')),

    path('note/', include('note.urls')),

    # for unauthorized access dynamic translation
    path('gtts/', include('gTTS.urls')),
    # for user authorized dynamic translation
    # path('gtts_auth/', include('gTTS.urls_auth')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

""" 
handler404 = 'dashboard.views.error_404'
handler500 = 'dashboard.views.error_500'
"""

mission/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [

    # we add the URL for the notes view, to output the list of notes.
    path('', views.missions, name="missions"),

    # we add the URL for the add view, to allow user to create notes.
    path('add/', views.addMission, name="addMission"),

    # we add the URL for the edit view, to allow user to update notes.
    path('edit/', views.editMission, name="editMission"),

    # we add the URL for the projects_delete to delete a project.
    path('<str:slug>/delete/', views.mission_delete, name="mission_delete"),

]

note/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [

    # we add the URL for the notes view, to output the list of notes.
    path('', views.notes, name="notes"),

    # we add the URL for the add view, to allow user to create notes.
    path('add/', views.addNote, name="addNote"),

    # we add the URL for the edit view, to allow user to update notes.
    path('edit/', views.editNote, name="editNote"),

    # we add the URL for the projects_delete to delete a project.
    path('<str:slug>/delete/', views.note_delete, name="note_delete"),

]

mission/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse
from model_utils import FieldTracker
from django.contrib.staticfiles.storage import staticfiles_storage

# Custom packages
import os
import re

from PIL import Image
import concurrent
import time
import datetime
from tqdm import tqdm

# My packages
from account.models import *
from hr_tech.settings import MEDIA_ROOT, BASE_DIR

Image.MAX_IMAGE_PIXELS = None


# Create your models here.

class Mission(models.Model):
    PRIME_CHOICES = (
        ('0', 'Pending'),
        ('1', 'Awarded'),
        ('2', 'Not Awarded'),
    )

    def get_upload_path(instance, filename):
        return 'missions/{0}/{1}'.format(instance.slug, filename)

    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=120, unique=True)
    slug = models.SlugField(unique=True)
    job_description = models.FileField(upload_to=get_upload_path, blank=True)
    prime = models.CharField(max_length=10, choices=PRIME_CHOICES, default='0')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    tracker = FieldTracker()

    def __str__(self):
        return str(self.title) + ' - ' + str(self.prime)

    class Meta:
        ordering = ['-updated_at']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)

        super(Mission, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return f"/mission/{self.slug}"

    def get_edit_url(self):
        return f"{self.get_absolute_url()}/edit"

mission/forms.py
from django import forms
# from django.contrib.auth.models import User
from .models import *
from account.models import User
import os


class MissionEditForm(forms.ModelForm):
    class Meta:
        model = Mission
        fields = ['title', 'job_description', 'prime']
        widgets = {
            'title': forms.TextInput(attrs={'readonly': 'readonly'}),
        }
        labels = {
            'title': 'Title'
        }


class MissionAddForm(forms.ModelForm):

    class Meta:
        model = Mission

        fields = ['title', 'job_description', 'prime']
        # fields = ['title', 'description']
        labels = {
            "title": "Mission Title",
            "job_description": "Description",
            "prime": "Prime"
        }

mission/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST, require_GET
from django.contrib import messages
from .models import *
from .forms import *
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.core.files.storage import FileSystemStorage
import datetime
from django.urls import reverse
import requests
import shutil
from django.db.models import Q


# Create your views here.

def missions(request):
    mission_list = Mission.objects.all()
    mForm = MissionAddForm()

    template_name = 'mission/missions.html'
    context = {
        'mission_list': mission_list,
        'mForm': mForm
    }
    # we return the template with the variables in context
    return render(request, template_name, context)


@login_required(redirect_field_name='login')
def editMission(request):
    user = request.user

    # form = NoteAddForm(data=request.POST)

    if request.method == 'POST':
        form = request.POST

    return True


@login_required(redirect_field_name='login')
@require_POST
@require_http_methods(["POST"])
def addMission(request):
    user = request.user

    form = MissionAddForm(data=request.POST, files=request.FILES)

    if form.is_valid():
        mForm = form.save(commit=False)
        mForm.author = user

        mForm.save()

        messages.success(request, 'Successfully added mission.')

    else:
        messages.warning(request, 'An error has occurred ! Please input the right information.')

    return redirect('missions')


# We create a view to delete a mission
@login_required(redirect_field_name='login')
def mission_delete(request, slug):
    # We request a user
    user = request.user
    # we retrieve the slug to retrieve the chosen mission
    mission = get_object_or_404(Mission, slug=slug)

    # We check if the current user has superuser status or has access to the mission
    if user.is_active and (user.is_superuser or mission.author == user):
        # We delete the mission
        mission.delete()
        # We retrieve the directory linked to the mission
        folder = os.path.join(BASE_DIR, 'media', 'missions', mission.slug)
        # We remove that directory as well
        shutil.rmtree(folder)

        messages.success(request, 'Successfully deleted mission.')
    else:
        messages.warning(request, 'Sorry you don\'t have permission to delete this mission! please contact your admin.')
    return redirect("missions")

mission/templates/mission/missions.html
{% extends 'base.html' %}

{% load gTTS %}

{% load static %}

{% load crispy_forms_tags %}

{% load crispy_forms_filters %}

{% block title %} Mission {% endblock %}

{% block head_css %}
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.css">
{% endblock %}

{% block content %}

    {% if messages %}
        {% for message in messages %}
        <div style="text-align: center;" class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>Hello! </strong> {{ message|safe }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    {% endif %}

    {% if request.user.is_authenticated %}
        
            <div style="text-align: right;">
                <a href="#addModal" data-toggle="modal" type="submit" style="color:#ffffff" class="btn btn-success btn-icon-split" >
                    <span class="icon text-white-50"><i class="fas fa-folder-plus"></i></span>
                    <span class="text">Add Mission</span>
                </a>
            </div>
        
    {% endif %}
    <hr>
    <div class='row'>
        <div style="width: 95%; margin: auto;" class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary"><i class="fas fa-list"></i> My Missions </h6>
            </div>
            <div class="card-body">
                {% if mission_list|length > 0 %}
                    <div class="card-body">
                        <table
                            class="table table-bordered"
                            id="dataTable"
                            width="100%"
                            cellspacing="0"
                            data-toggle="table"
                            data-search="true"
                            data-show-refresh="true"
                            data-show-toggle="true"
                            data-show-fullscreen="true"
                            data-show-columns="true"
                            data-show-columns-toggle-all="false"
                            data-click-to-select="true"
                            data-minimum-count-columns="2"
                            data-show-pagination-switch="true"
                            data-pagination="true"
                            data-id-field="name"
                            data-page-list="[10, 25, 50, 100, all]"
                            data-detail-view="true"
                            data-detail-formatter="detailService"
                            data-show-export="true"
                            data-export-options='{"fileName": "Mission"}'>
                            <thead>
                                <tr>
                                    <th data-field="id" data-visible="false" >ID</th>
                                    <th data-field="name" data-sortable="true" >Title</th>
                                    <th data-field="owner" data-visible="false" >Job description</th>
                                    <th data-field="access" data-sortable="true" data-visible="true" >Prime</th>
                                    <th data-field="created_at" data-visible="false" > Created at</th>
                                    <th data-field="action" >Open</th>
                                    <th data-field="link" data-visible="false">Link</th>
                                    <th data-field="delete" style="text-align: center;">Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for mission in mission_list %}
                                    <tr>
                                        <td>{{ mission.id }}</td>
                                        <td>{{ mission.title }}</td>
                                        <td>{{ mission.description }}</td>
                                        <td>{{ mission.get_prime_display }}</td>
                                        <td>{{ mission.created_at }}</td>

                                        <td> <a href="{{ mission.get_absolute_url }}"> Open</a></td>
                                        <td>{{ mission.get_absolute_url }}</td>

                                        <td style="text-align: center;" >
                                            <div class="text-center">
                                                <a id="deleteMission" data-toggle="modal" data-slug="{{ mission.slug }}" data-target="#deleteModal" class="" href='{{ mission.get_delete_url }}'>
                                                    <i style="color: #e74a3b;" class="fas fa-times fa-2x" ></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>

                {% else %}
                    <div style="display: flex; height: 50vh; width: 100%; justify-content: center; align-items: center; font-size: 1.4em;">
                        No mission added
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    <!-- Add Note Modal-->
    <div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Add Mission</h5>
              <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
              </button>
            </div>
            <div class="modal-body">

                <div class="card-body">

                    <form style="grid-area: form; width: 90%; margin: auto;" method='POST'  action="{% url 'addMission' %}" enctype="multipart/form-data">
                        {% csrf_token %}

                        {{ mForm|crispy}}

                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>

                        <button type='submit' class="float-right btn btn-primary btn-user">
                            <i class="fas fa-plus-circle"></i>
                            Add mission
                        </button>

                    </form>

                </div>


            </div>
            <div class="modal-footer">
            </div>
          </div>
        </div>
      </div>
    
    <!-- Delete Mission Modal-->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Delete Mission Definitely?</h5>
              <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
              </button>
            </div>
            <div class="modal-body">
                Select "Delete" below if you want to delete the mission definitely.
                <i class="fas fa-exclamation-triangle"> This action cannot be undone!</i>
            </div>
            <div class="modal-footer">
              <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
              <a class="btn btn-danger btn-icon-split" href="">
                <span class="icon text-white-50"> <i class="fas fa-trash"></i></span>
                <span class="text">Delete</span>
              </a>
            </div>
          </div>
        </div>
      </div>


{% endblock %}


{% block javascript %}

    <script src="https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.16.0/dist/extensions/export/bootstrap-table-export.min.js"></script>

    <script type="text/javascript">

        function detailService (value, row, index) {
            return [
                '<div>',
                    '<table style="width=100%" class="table"> ',
                        '<tbody>',
                                '<th scope="created_at">Description</th>',
                                '<td>',
                                    row.job_description,
                                '</td>',

                                '<th scope="created_at">Created at</th>',
                                '<td>',
                                    row.created_at,
                                '</td>',

                            '</tr>',
                        '</tbody>',
                    '</table>',
                '</div>',
            ].join('');
        }


        $(document).ready(function(){
            $(document).on("click", "#deleteMission", function () {

                var prjSlug = $(this).data('slug');
                console.log(prjSlug);
                var my_link = "{% url 'mission_delete' slug='9999999999999'  %}"
                var link = my_link.replace('9999999999999', prjSlug);
                $('#deleteModal').find('.modal-footer a')[0].href = link
            });

            $('#dataTable').on('dbl-click-row.bs.table', function (e, row, $element) {
                var url = row.link;
                // alert(url)
                window.location.href = url;
            });

            $('#dataTable').on('refresh.bs.table', function (params) {
                window.location.reload();
            });
        });
      </script>
{% endblock %}