hr_tech/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('account/', include('account.urls')),

    path('', include('dashboard.urls')),

    path('candidate/', include('candidat.urls')),

    path('mission/', include('mission.urls')),

    path('note/', include('note.urls')),

    # for unauthorized access dynamic translation
    path('gtts/', include('gTTS.urls')),
    # for user authorized dynamic translation
    # path('gtts_auth/', include('gTTS.urls_auth')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

""" 
handler404 = 'dashboard.views.error_404'
handler500 = 'dashboard.views.error_500'
"""

note/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [

    # we add the URL for the notes view, to output the list of notes.
    path('', views.notes, name="notes"),

    # we add the URL for the add view, to allow user to create notes.
    path('add/', views.addNote, name="addNote"),

    # we add the URL for the edit view, to allow user to update notes.
    path('edit/', views.editNote, name="editNote"),

    # we add the URL for the projects_delete to delete a project.
    path('<str:slug>/delete/', views.note_delete, name="note_delete"),

]

note/models.py
# Django packages
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse
from model_utils import FieldTracker
from django.contrib.staticfiles.storage import staticfiles_storage


# Custom packages
import os
import re

from PIL import Image
import concurrent
import time
import datetime
from tqdm import tqdm


# My packages
from account.models import *
from hr_tech.settings import MEDIA_ROOT, BASE_DIR

Image.MAX_IMAGE_PIXELS = None

# Create your models here.


class Note(models.Model):
    LANGUAGE_CHOICES = (
        ('fr', 'Français'),
        ('en-uk', 'English (uk)'),
        ('en-us', 'English (usa)'),
    )

    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=120, unique=True)
    slug = models.SlugField(unique=True)
    description = models.TextField(null=True, blank=True)
    language = models.CharField(max_length=10, choices=LANGUAGE_CHOICES, default='fr')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    tracker = FieldTracker()

    def __str__(self):
        return str(self.title) + ' - ' + str(self.language)

    class Meta:
        ordering = ['-updated_at']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)

        super(Note, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return f"/note/{self.slug}"

    def get_edit_url(self):
        return f"{self.get_absolute_url()}/edit"




'''

    Mission
        title 
        slug
        pdf fiche de poste
        commentaire
        prime 
    
    
    Candidat
        nom 
        prenom 
        email 
        titre 
        numero 	
        mission 
    
    
    Notes 
        title 
        slug 
        description 
        langue
	
'''

note/forms.py
from django import forms
# from django.contrib.auth.models import User
from .models import *
from account.models import User
import os


class NoteEditForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'language', 'description']
        widgets = {
            'title': forms.TextInput(attrs={'readonly': 'readonly'}),
        }
        labels = {
            'title': 'Title'
        }


class NoteAddForm(forms.ModelForm):

    # language = forms.ChoiceField(choices=LANGUAGE_CHOICES)

    class Meta:
        model = Note

        LANGUAGE_CHOICES = (
            ('fr', 'Français'),
            ('en-uk', 'English (uk)'),
            ('en-us', 'English (usa)'),
        )

        fields = ['title', 'language', 'description']
        # fields = ['title', 'description']
        labels = {
            "title": "Note Title",
            "language": "Language",
            "description": "Description"
        }
        """ 
        widgets = {
            'language': forms.ChoiceField(
                choices=LANGUAGE_CHOICES,
                label="Language",
                required=True,
                help_text="The language of which your note is"
            )
        }
        """

note/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST, require_GET
from django.contrib import messages
from .models import *
from .forms import *
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.core.files.storage import FileSystemStorage
import datetime
from django.urls import reverse
import requests
from django.db.models import Q


# Create your views here.

def notes(request):
    note_list = Note.objects.all()
    nForm = NoteAddForm()

    template_name = 'note/notes.html'
    context = {
        'note_list': note_list,
        'nForm': nForm
    }
    # we return the template with the variables in context
    return render(request, template_name, context)


@login_required(redirect_field_name='login')
def editNote(request):
    user = request.user

    # form = NoteAddForm(data=request.POST)

    if request.method == 'POST':
        form = request.POST

    return True


@login_required(redirect_field_name='login')
@require_POST
@require_http_methods(["POST"])
def addNote(request):
    user = request.user

    form = NoteAddForm(data=request.POST)

    if form.is_valid():
        nForm = form.save(commit=False)
        nForm.author = user

        nForm.save()

        messages.success(request, 'Successfully added note.')

    else:
        messages.warning(request, 'An error has occurred ! Please input the right information.')

    return redirect('notes')


# We create a view to delete a note
@login_required(redirect_field_name='login')
def note_delete(request, slug):
    # We request a user
    user = request.user
    # we retrieve the slug to retrieve the chosen project
    note = get_object_or_404(Note, slug=slug)

    # We check if the current user has superuser status or has access to the project
    if user.is_active and (user.is_superuser or note.author == user):
        # We delete the note
        note.delete()

        messages.success(request, 'Successfully deleted note.')
    else:
        messages.warning(request, 'Sorry you don\'t have permission to delete this note! please contact your admin.')
    return redirect("notes")

note/templates/note/notes.html
{% extends 'base.html' %}

{% load gTTS %}

{% load static %}

{% load crispy_forms_tags %}

{% load crispy_forms_filters %}

{% block title %} Note {% endblock %}

{% block head_css %}
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.css">
{% endblock %}

{% block content %}

    {% if messages %}
        {% for message in messages %}
        <div style="text-align: center;" class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>Hello! </strong> {{ message|safe }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    {% endif %}

    {% if request.user.is_authenticated %}
        
            <div style="text-align: right;">
                <a href="#addModal" data-toggle="modal" type="submit" style="color:#ffffff" class="btn btn-success btn-icon-split" >
                    <span class="icon text-white-50"><i class="fas fa-folder-plus"></i></span>
                    <span class="text">Add Note</span>
                </a>
            </div>
        
    {% endif %}
    <hr>
    <div class='row'>
        <div style="width: 95%; margin: auto;" class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary"><i class="fas fa-list"></i> My Notes </h6>
            </div>
            <div class="card-body">
                {% if note_list|length > 0 %}
                    <div class="card-body">
                        <table
                            class="table table-bordered"
                            id="dataTable"
                            width="100%"
                            cellspacing="0"
                            data-toggle="table"
                            data-search="true"
                            data-show-refresh="true"
                            data-show-toggle="true"
                            data-show-fullscreen="true"
                            data-show-columns="true"
                            data-show-columns-toggle-all="false"
                            data-click-to-select="true"
                            data-minimum-count-columns="2"
                            data-show-pagination-switch="true"
                            data-pagination="true"
                            data-id-field="name"
                            data-page-list="[10, 25, 50, 100, all]"
                            data-detail-view="true"
                            data-detail-formatter="detailService"
                            data-show-export="true"
                            data-export-options='{"fileName": "Notes"}'>
                            <thead>
                                <tr>
                                    <th data-field="id" data-visible="false" >ID</th>
                                    <th data-field="name" data-sortable="true" >Title</th>
                                    <th data-field="owner" data-sortable="true" data-visible="true" >Language</th>
                                    <th data-field="access" data-sortable="true" data-visible="true" >Description</th>
                                    <th data-field="created_at" data-visible="false" > Created at</th>
                                    <th data-field="read" data-visible="false">Read</th>
                                    <th data-field="action" >Open</th>
                                    <th data-field="link"  data-visible="false" >Link</th>
                                    <th data-field="delete" style="text-align: center;">Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for note in note_list %}
                                    <tr>
                                        <td>{{ note.id }}</td>
                                        <td>{{ note.title }}</td>
                                        <td>{{ note.get_language_display }}</td>
                                        <td>{{ note.description }}</td>
                                        <td>{{ note.created_at  }}</td>

                                        <td>
                                            to come
                                            <!--
                                            {#  <audio src="{% say note.language note.description %}" controls></audio> #}
                                            -->
                                        </td>

                                        <td> <a href="{{ note.get_absolute_url }}"> Open</a></td>
                                        <td>{{ note.get_absolute_url }}</td>

                                        <td style="text-align: center;" >
                                            <div class="text-center">
                                                <a id="deleteNote" data-toggle="modal" data-slug="{{ note.slug }}" data-target="#deleteModal" class="" href='{{ note.get_delete_url }}'>
                                                    <i style="color: #e74a3b;" class="fas fa-times fa-2x" ></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>

                {% else %}
                    <div style="display: flex; height: 50vh; width: 100%; justify-content: center; align-items: center; font-size: 1.4em;">
                        No note added
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    <!-- Add Note Modal-->
    <div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Add Note</h5>
              <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
              </button>
            </div>
            <div class="modal-body">

                <div class="card-body">

                    <form style="grid-area: form; width: 90%; margin: auto;" method='POST'  action="{% url 'addNote' %}">
                        {% csrf_token %}

                        {{ nForm|crispy}}

                        <button type='submit' class="float-right btn btn-primary btn-user">
                            <i class="fas fa-plus-circle"></i>
                            Add note
                        </button>

                    </form>

                </div>


            </div>
            <div class="modal-footer">
              <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
              <a class="btn btn-danger btn-icon-split" href="">
                <span class="icon text-white-50"> <i class="fas fa-trash"></i></span>
                <span class="text">Add</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    
    <!-- Delete Note Modal-->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Delete Note Definitely?</h5>
              <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
              </button>
            </div>
            <div class="modal-body">
                Select "Delete" below if you want to delete the note definitely.
                <i class="fas fa-exclamation-triangle"> This action cannot be undone!</i>
            </div>
            <div class="modal-footer">
              <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
              <a class="btn btn-danger btn-icon-split" href="">
                <span class="icon text-white-50"> <i class="fas fa-trash"></i></span>
                <span class="text">Delete</span>
              </a>
            </div>
          </div>
        </div>
      </div>


{% endblock %}


{% block javascript %}

    <script src="https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.16.0/dist/extensions/export/bootstrap-table-export.min.js"></script>

    <script type="text/javascript">

        function detailService (value, row, index) {
            return [
                '<div>',
                    '<table style="width=100%" class="table"> ',
                        '<tbody>',
                                '<th scope="read">Read</th>',
                                '<td>',
                                    row.read,
                                '</td>',
                                '<th scope="created_at">Created at</th>',
                                '<td>',
                                    row.created_at,
                                '</td>',

                            '</tr>',
                        '</tbody>',
                    '</table>',
                '</div>',
            ].join('');
        }


        $(document).ready(function(){
            $(document).on("click", "#deleteNote", function () {

                var prjSlug = $(this).data('slug');
                console.log(prjSlug);
                var my_link = "{% url 'note_delete' slug='9999999999999'  %}"
                var link = my_link.replace('9999999999999', prjSlug);
                $('#deleteModal').find('.modal-footer a')[0].href = link
            });

            $('#dataTable').on('dbl-click-row.bs.table', function (e, row, $element) {
                var url = row.link;
                // alert(url)
                window.location.href = url;
            });

            $('#dataTable').on('refresh.bs.table', function (params) {
                window.location.reload();
            });
        });
      </script>
{% endblock %}