hr_tech/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('account/', include('account.urls')),

    path('', include('dashboard.urls')),

    path('candidate/', include('candidat.urls')),

    path('mission/', include('mission.urls')),

    path('note/', include('note.urls')),

    # for unauthorized access dynamic translation
    path('gtts/', include('gTTS.urls')),
    # for user authorized dynamic translation
    # path('gtts_auth/', include('gTTS.urls_auth')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

""" 
handler404 = 'dashboard.views.error_404'
handler500 = 'dashboard.views.error_500'
"""

note/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [

    # we add the URL for the notes view, to output the list of notes.
    path('', views.notes, name="notes"),

    # we add the URL for the add view, to allow user to create notes.
    path('add/', views.addNote, name="addNote"),

    # we add the URL for the edit view, to allow user to update notes.
    path('edit/', views.editNote, name="editNote"),

    # we add the URL for the projects_delete to delete a project.
    path('<str:slug>/delete/', views.note_delete, name="note_delete"),

]

account/models.py
from django.db import models 
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import Group


# Create your models here.

class User(AbstractUser):
    
    ACCOUNT_TYPE_CHOICES = ( 
        ('0', 'manager'),
        ('1', 'recruiter'),
        ('2', 'developer')
    )

    def get_upload_path(instance, filename):
        return 'users/{0}/{1}'.format(instance.username, filename)
    
    email = models.EmailField(unique=True)
    account_type = models.CharField(max_length=10, choices=ACCOUNT_TYPE_CHOICES, default='1')

    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to=get_upload_path, blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.username


class AllowRegistration(models.Model):

    name = models.CharField(max_length=120, db_index=True, unique=True, default='user_registration') 
    status = models.BooleanField(default=True)

    def __str__(self):
        if self.status: 
            return str(self.name) + str(' - abled')
        else:
            return str(self.name) + str(' - disabled')

templates/base.html
<!DOCTYPE html>

{% load static %}

{% load crispy_forms_tags %}

<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="Dieuveille BOUSSA ELLENGA">

        <link rel="icon" type="image/png" href="{% static 'assets/img/hr-tech-icon.ico' %}"/>

        <title>{% block title %} {% endblock %}   |   HR TECH</title>

        <!-- Custom fonts for this template-->
        <link href="{% static 'assets/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

        <!-- Custom styles for this template-->
        <link href="{% static 'assets/css/sb-admin-2.css' %}" rel="stylesheet">
        <link href="{% static 'assets/css/image-picker.css' %}" rel="stylesheet" type="text/css">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">

        <style>
          div#search-dropdown-menu a.dropdown-item.active{
            color: rgb(136, 130, 130);
          }

        </style>


        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

        {% block head_css %}
        {% endblock %}

        {% block head_javascript %}
        {% endblock %}
    </head>

    <body id="page-top">

        <!-- Page Wrapper -->
        <div id="wrapper">

            <!-- Sidebar -->
            <ul class="navbar-nav bg-gradient-Amine-Style sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->

                <div class="col-xs-12  u-padding-l-0 mobile-nav-controls-container">
                    <a href="{% url 'dashboard' %}"><img class="site-logo" style="width:80%;padding: 0px 10px 5px 15px" src="{% static 'assets/img/logo.png' %}" alt="HR-TECH"></a>
                </div>
                <!-- Divider -->
                <hr class="sidebar-divider my-0">

                <!-- Divider -->
                <hr class="sidebar-divider">
                <!-- Nav Item - Charts -->
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'dashboard' %}">
                        <i class="fas fa-fw fa-tachometer-alt"></i>
                        <span>Dashboard</span>
                    </a>
                </li>

                <hr class="sidebar-divider">
                <!-- Heading -->
                <div class="sidebar-heading">
                    Extraction
                </div>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'candidates' %}">
                        <i class="fas fa-user-plus"></i>
                        <span>Candidates</span>
                    </a>
                </li>

                <!-- Nav Item - Charts -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'missions' %}">
                        <i class="fas fa-fw fa-tasks"></i>
                        <span>Missions</span>
                    </a>
                </li>

                <!-- Nav Item - Charts -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'notes' %}">
                        <i class="fas fa-fw fa-file"></i>
                        <span>Notes</span>
                    </a>
                </li>


                <hr class="sidebar-divider">
                <!-- Heading -->
                <div class="sidebar-heading">
                    Simulation
                </div>

                <!-- Nav Item - Charts -->
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <i class="fas fa-fw fa-chart-area"></i>
                        <span>Statistics</span>
                    </a>
                </li>

                <!-- Nav Item - Tables -->
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <i class="fas fa-fw fa-chart-line"></i>
                        <span>Simulator</span>
                    </a>
                </li>

                <hr class="sidebar-divider">
                <!-- Heading -->
                <div class="sidebar-heading">
                    Management
                </div>

                {% if user.is_superuser or user.get_account_type_display == 'manager' %}
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <i class="fas fa-user-shield"></i>
                        <span>Access management</span>
                    </a>
                </li>
                {% endif %}

                {% if user.is_superuser or user.get_account_type_display == 'manager' %}
                <li class="nav-item">
                    <a class="nav-link"  href="/admin/account/user" target="_blank">
                        <i class="fas fa-fw fa-users"></i>
                        <span>Users management</span>
                    </a>
                </li>
                {% endif %}

                <!-- Nav Item - Tables -->
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <i class="fas fa-fw fa-cog"></i>
                        <span>Feature Settings</span>
                    </a>
                </li>

                 <!-- Nav Item - Tables -->
                <!--
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <i class="fas fa-fw fa-search"></i>
                    <span>PDF Manual Extraction</span></a>
                </li>
                -->

                <!-- Nav Item - Tables -->
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <i class="fas fa-question"></i>
                    <span>Help</span></a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <i class="fas fa-fw fa-info-circle"></i>
                    <span>About</span></a>
                </li>
                <!-- Divider -->
                <hr class="sidebar-divider d-none d-md-block">
                <!-- Sidebar Toggler (Sidebar) -->
                <div class="text-center d-none d-md-inline">
                  <button class="rounded-circle border-0" id="sidebarToggle"></button>
                </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
          <!-- Topbar -->
          <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
            <!-- Sidebar Toggle (Topbar) -->
            <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
              <i class="fa fa-bars"></i>
            </button>
            <!-- Topbar Search -->
            <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" method="GET" action="#">
              <div class="input-group">
                <div class="input-group-append">
                  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    <span id="search_concept">All Projects</span> <span class="caret"></span>
                  </button>
                  <div id="search-dropdown-menu" class="dropdown-menu">
                    <a  class="dropdown-item active" data-id="0" >All Project</a>
                      {% for p in all_projects%}
                        <a  class="dropdown-item" data-id="{{p.id}}" >{{p.title}}</a>
                      {% endfor %}
                  </div>
                </div>
                <input id="search_input_hidden" name='project' value="0" type="hidden" >
                <input id="search_input_folder_hidden" name='folders' value="all" type="hidden" >
                <input id="search_input" name='query' type="text" class="form-control bg-light border-0 small" required placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                  <button class="btn btn-primary" type="submit">
                    <i class="fas fa-search fa-sm"></i>
                  </button>
                </div>
              </div>
            </form>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="mr-2-my-gradient">{{ user.username }}</span>
                    <img
                            {% if request.user.photo %}
                                src="{{request.user.photo.url}}" alt="{{user.username}} Avatar" class="rounded-circle avatar-sm" style="width:15%"
                            {% else %}
                                src="{% static 'assets/img/technip_energies_60.png' %}" style="width:45%" alt="Default Avatar"
                            {% endif %}
                    >
                </a>

                <!-- Dropdown - User Information -->
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                    {% if user.is_staff %}
                        <a class="dropdown-item" target="_blank" href="{% url 'admin:index' %}">
                            <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                              Administration
                        </a>

                        <div class="dropdown-divider"></div>
                    {% endif %}
                    <a class="dropdown-item" href="{% url 'profile' %}">
                        <i class="fas fa-user-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Manage Account
                    </a>

                    <div class="dropdown-divider"></div>

                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Logout
                    </a>
                </div>

              </li>
            </ul>
          </nav>
          <!-- End of Topbar -->
          <!-- Begin Page Content -->
          <div class="container-fluid">
            <!-- Page Heading -->
            <h1 class="h3 mb-4 text-gray-800">{% block page_name %}{% endblock %}</h1>
            {% block content %}
            {% endblock %}
          </div>
          <!-- /.container-fluid -->
        </div>
        <!-- End of Main Content -->
        <!-- Footer -->
        <footer class="sticky-footer bg-white">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span> © <script>document.write(new Date().getFullYear())</script> HR TECH. </span>
            </div>
          </div>
        </footer>
        <!-- End of Footer -->
        </div>
        <!-- End of Content Wrapper -->
        </div>
        <!-- End of Page Wrapper -->

        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
        </a>
        <!-- Logout Modal-->
        <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to log out.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
          </div>
        </div>
        </div>
        </div>

        <!-- Bootstrap core JavaScript-->
        <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <!-- Core plugin JavaScript-->
        <script src="{% static 'assets/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
        <!-- Custom scripts for all pages-->
        <script src="{% static 'assets/js/sb-admin-2.min.js' %}"></script>
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

        <script type="text/javascript">

        </script>

        {% block javascript %}
        {% endblock %}
    </body>
</html>